ca-cwds/jobs

cals/build.gradle, cals/src/main/resources/log4j.properties, cals/src/test/java/gov/ca/cwds/jobs/cals/facility/ChangedFacilityResourceTest.java, cals/src/test/java/gov/ca/cwds/jobs/cals/rfa/ChangedRFA1aFormsResourceTest.java
tuned logger configuration;
fixed tests;
=> fixed dependency;

build.gradle, src/main/java/gov/ca/cwds/dao/ApiClientCountyAware.java, src/main/java/gov/ca/cwds/data/persistence/cms/BaseEsClient.java, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java, src/main/java/gov/ca/cwds/neutron/util/transform/ElasticTransformer.java, src/test/java/gov/ca/cwds/data/persistence/cms/EsClientAddressTest.java, src/test/java/gov/ca/cwds/data/persistence/cms/EsClientTest.java, src/test/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClientTest.java, src/test/java/gov/ca/cwds/jobs/test/TestNormalizedEntity.java, src/test/java/gov/ca/cwds/neutron/util/transform/ElasticTransformerTest.java
Added logic to index multiple client counties in "client_counties" field. Updated to latest api-core. Update phone numbers to be Long instead of BigDecimal.
=> Added multiple client counties

src/main/java/gov/ca/cwds/neutron/rocket/cases/CaseSQLResource.java
=> INT-1518: Limit relationship types linked to Case History

src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java, src/main/java/gov/ca/cwds/jobs/ReferralHistoryIndexerJob.java
INT-1413: Phone and "other mailing address"
Includes Referrals fix for DB2 "with uncommitted read" ("WITH UR").
=> Dave int 1413

jobs-common/src/main/java/gov/ca/cwds/jobs/common/elastic/ElasticWriter.java, jobs-facilities-cws/config/cws-facility-job.yaml, jobs-facilities-lis/config/lis-facility-job.yaml
configuration files improvements;
no task for those changes
=> items counter improvements;

build.gradle, jobs-facilities-cws/src/test/resources/fixtures/cwsrs_deleted_facility.json, jobs-facilities-cws/src/test/resources/fixtures/cwsrs_new_facility.json, jobs-facilities-cws/src/test/resources/fixtures/cwsrs_updated_facility.json, jobs-facilities-cws/src/test/resources/fixtures/facilities-initial-load-cwscms.json, jobs-facilities-lis/src/test/resources/fixtures/facilities-initial-load-lis.json, jobs-facilities-lis/src/test/resources/fixtures/lis_updated_facility.json
a new version of CALS-API
fix fixtures according to the new data model
=> CALS-5645 Placement Home read/search: implement DocTool rule R - 05184

src/main/java/gov/ca/cwds/neutron/flight/FlightPlan.java, src/main/java/gov/ca/cwds/neutron/flight/NeutronCmdLineOption.java, src/main/java/gov/ca/cwds/neutron/inject/HyperCube.java, src/main/java/gov/ca/cwds/neutron/launch/StandardFlightSchedule.java, src/main/java/gov/ca/cwds/neutron/rocket/LetsLightThisCandleRocket.java
INT-1610: decommission of People Index. "-N" flag fixed.
"-N": don't run any People index jobs.
"-e referral,case,relationship": exclude listed jobs.
=> Neutron no people index

src/test/java/gov/ca/cwds/neutron/launch/StandardFlightScheduleTest.java
=> INT-1610: exclude Neutron rockets: JUnit fix

build.gradle, src/main/resources/neutron/elasticsearch/mapping/map_person_summary.json
- [INT-1711:Add Middle Names and Suffixes to Elastic Search](https://osi-cwds.atlassian.net/browse/INT-1711)
Add Middle Names and Suffixes to Elastic Search
Additional information is available in 
- [INT-1665:SPIKE: Implications for search enhancements](https://osi-cwds.atlassian.net/browse)
=> INT-1711 Add Middle Names and Suffixes to Elastic Search

jobs-facilities-cws/config/unix_cws_facility-job.yaml, jobs-facilities-cws/unix_cws_facility_index.sh, jobs-facilities-lis/config/unix_lis-facility-job.yaml, jobs-facilities-lis/unix_lis_facility_index.sh
fixed configuration and run scripts;
=> CALS-5936: No Facilities Found when Using Facility Type as a Filter Criteria

jobs-facilities-lis/src/main/java/gov/ca/cwds/jobs/cals/facility/lis/LisRecordChange.java
=> SEAR-85: Non-Children's Residential Facilities removed from Facilities index

build.gradle, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java
Integrated name suffix translations
=> Integrated name suffix translations

src/main/java/gov/ca/cwds/data/persistence/cms/BaseEsClient.java, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClientAddress.java, src/main/java/gov/ca/cwds/jobs/ClientPersonIndexerJob.java, src/main/java/gov/ca/cwds/neutron/atom/AtomInitialLoad.java, src/main/java/gov/ca/cwds/neutron/rocket/BasePersonRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/SchemaResetRocket.java, src/test/java/gov/ca/cwds/jobs/ClientSummaryIndexerJobTest.java, src/test/java/gov/ca/cwds/jobs/schedule/LaunchCommandTest.java, src/test/java/gov/ca/cwds/jobs/test/Mach1TestRocket.java
Minor requirements update: store *all* active addresses in People Summary and sort by:
1. placement home
2. residence
3. other address type
4. start date
=> Dave snap 29

build.gradle, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClientAddress.java, src/main/resources/neutron/elasticsearch/mapping/map_person_summary.json
=> Dave igor snap 46

build.gradle
Used latest api-core to fix name suffix translation.
https://osi-cwds.atlassian.net/browse/HOT-1975
=> Used latest api-core to fix name suffix translation.

src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java
Added placement home phone numbers to the main list of phone numbers
=> HOT-1988 Neutron and Elastic Search changes for most recent phone number

build.gradle, src/main/java/gov/ca/cwds/data/es/NeutronElasticSearchPerson.java, src/main/java/gov/ca/cwds/data/persistence/cms/PlacementHomeAddress.java, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java, src/main/java/gov/ca/cwds/jobs/ClientPersonIndexerJob.java, src/main/java/gov/ca/cwds/neutron/rocket/CaseRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/ClientSQLResource.java, src/main/java/gov/ca/cwds/neutron/rocket/IndexResetRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/SchemaResetRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/cases/CaseSQLResource.java, src/test/java/gov/ca/cwds/data/persistence/cms/PlacementHomeAddressTest.java, src/test/java/gov/ca/cwds/data/persistence/cms/rep/CmsReplicatedEntityTest.java, src/test/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClientAddressTest.java, src/test/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClientTest.java, src/test/java/gov/ca/cwds/jobs/Goddard.java, src/test/java/gov/ca/cwds/jobs/ReferralHistoryIndexerJobTest.java, src/test/java/gov/ca/cwds/jobs/test/SimpleTestSystemCodeCache.java, src/test/java/gov/ca/cwds/neutron/rocket/CaseRocketTest.java, src/test/java/gov/ca/cwds/neutron/rocket/PeopleSummaryThreadHandlerTest.java, src/test/java/gov/ca/cwds/neutron/rocket/SchemaResetRocketTest.java
=> Dave junit sonar

src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedOtherAdultInPlacemtHome.java, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedOtherChildInPlacemtHome.java
bug fix for other adult/child in home no coming to the index
=> Igor hot 1732 - Index non-client people to people-summary index

build.gradle
=> HOT-2030 Resolve bug in Other Adult/Child in home

build.gradle, src/main/java/gov/ca/cwds/neutron/util/transform/ElasticTransformer.java
Jira: https://osi-cwds.atlassian.net/browse/HOT-2029
=> Added date of death to index

src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryLastChangeHandler.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryThreadHandler.java
Minor patch before going to Preint and Integration.
=> SNAP-159: Production people summary out of memory

build.gradle, src/main/java/gov/ca/cwds/jobs/ClientPersonIndexerJob.java, src/main/java/gov/ca/cwds/neutron/flight/FlightPlan.java, src/main/java/gov/ca/cwds/neutron/flight/NeutronCmdLineOption.java, src/main/java/gov/ca/cwds/neutron/flight/NeutronCmdLineParser.java, src/main/java/gov/ca/cwds/neutron/flight/NeutronLongCmdLineName.java, src/main/java/gov/ca/cwds/neutron/rocket/LastFlightRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryLastChangeHandler.java, src/main/java/gov/ca/cwds/neutron/util/jdbc/WorkSetDB2UserInfo.java
Highlights:
- Javadoc for various classes
- Added JUnits
- Fixed SonarQube
- Improved logging in PeopleSummaryLastChangeHandler
=> Dave sonar junit javadoc

build.gradle, src/main/java/gov/ca/cwds/dao/ApiClientCaseAware.java, src/main/java/gov/ca/cwds/data/persistence/cms/EsClientPerson.java, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java, src/main/java/gov/ca/cwds/neutron/rocket/ClientSQLResource.java, src/main/java/gov/ca/cwds/neutron/util/transform/ElasticTransformer.java, src/test/java/gov/ca/cwds/jobs/test/TestNormalizedEntity.java
Added open case responsible agency code
=> Added open case responsible agency code

src/main/java/gov/ca/cwds/neutron/launch/LaunchPad.java
Minor SonarQube hiccup after merge to master.
=> SNAP-265: SonarQube

src/main/java/gov/ca/cwds/neutron/inject/HyperCube.java, src/main/java/gov/ca/cwds/neutron/rocket/BasePersonRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/CaseRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/ClientSQLResource.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryLastChangeHandler.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryThreadHandler.java, src/main/java/gov/ca/cwds/neutron/rocket/SchemaResetRocket.java, src/main/java/gov/ca/cwds/neutron/util/NeutronThreadUtils.java, src/main/java/gov/ca/cwds/neutron/util/jdbc/NeutronJdbcUtils.java, src/test/java/gov/ca/cwds/neutron/rocket/PeopleSummaryLastChangeHandlerTest.java
=> Dave SNAP-339 more sonar

src/main/java/com/google/inject/NeutronGuiceModule.java, src/main/java/gov/ca/cwds/neutron/enums/FlightStatus.java, src/main/java/gov/ca/cwds/neutron/flight/FlightLog.java, src/main/java/gov/ca/cwds/neutron/inject/HyperCube.java, src/main/java/gov/ca/cwds/neutron/rocket/LastFlightRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryLastChangeHandler.java, src/test/java/com/google/inject/name/NeutronTestGuiceHiddenClassHandler.java, src/test/java/gov/ca/cwds/neutron/inject/HyperCubeTest.java, src/test/resources/test-h2-cms.xml
Ensure that timestamp files are updated on successful job runs.
Additional work on JUnits, especially HyperCube.
=> Dave SNAP-340

src/test/java/gov/ca/cwds/jobs/CollateralIndividualIndexerJobTest.java, src/test/java/gov/ca/cwds/jobs/OtherClientNameIndexerJobTest.java, src/test/java/gov/ca/cwds/jobs/RelationshipIndexerJobTest.java, src/test/java/gov/ca/cwds/jobs/ReporterIndexerJobTest.java, src/test/java/gov/ca/cwds/neutron/rocket/BasePersonRocketTest.java
JUnits for recent end date changes.
=> Dave SNAP-340 junit

build.gradle
=> ES shard and replica settings

src/main/resources/neutron/elasticsearch/setting/people-summary-index-settings.json
=> ES index setting tuning

build.gradle, src/main/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClient.java, src/main/resources/neutron/elasticsearch/mapping/map_person_summary.json, src/test/java/gov/ca/cwds/data/persistence/cms/rep/ReplicatedClientTest.java
- [HOT-2416:Change Neutron mapping and re-index for address queries](https://osi-cwds.atlassian.net/browse/HOT-2416)
Added index mapping and code for Elasticsearch people-summary Index to facilitate search by Last Known Address
N/A
N/A
=> HOT-2416 Change Neutron mapping and re-index for address queries

build.gradle
Increment Neutron version by sprint and distinguish new development work from current Production.
=> Increment Neutron version

build.gradle, src/main/java/gov/ca/cwds/dao/cms/NeutronSystemCodeDao.java, src/main/java/gov/ca/cwds/neutron/flight/FlightLog.java, src/main/java/gov/ca/cwds/neutron/flight/NeutronWarningTracker.java, src/main/java/gov/ca/cwds/neutron/inject/HyperCube.java, src/main/java/gov/ca/cwds/neutron/inject/NeutronSystemCodeCache.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryThreadHandler.java, src/test/java/gov/ca/cwds/neutron/inject/NeutronSystemCodeCacheTest.java
Load all system codes up front to prevent connection leaks.
=> Dave COG-591

src/test/java/gov/ca/cwds/neutron/rocket/PeopleSummaryLastChangeHandlerTest.java
=> SNAP-729: Neutron Initial Load: restore CSEC

build.gradle, src/main/java/gov/ca/cwds/data/persistence/cms/client/RawClient.java
Elasticsearch person documents are missing language and SSN.
Section of code was not migrated from class BaseEsClient to RawClient.
=> Dave SNAP-731

build.gradle, src/main/java/gov/ca/cwds/jobs/ReportFaultCANSClientIdsJob.java
[CANS-746 CANS v1.0 Assessments with wrong Client ID #](https://osi-cwds.atlassian.net/browse/CANS-746)
=> CANS-746 CANS v1.0 Assessments with wrong Client ID #

src/main/java/gov/ca/cwds/jobs/ReportFaultCANSClientIdsJob.java
Foll back to report only mode when RS connection isn't provided. Backward compatibility with deployment scripts done for report only.
=> CANS-777 Update CANS Postgres for Merges of Client Records in CWS/CMS

build.gradle, src/main/java/gov/ca/cwds/jobs/ClientPersonIndexerJob.java, src/main/java/gov/ca/cwds/neutron/atom/AtomLaunchDirector.java, src/main/java/gov/ca/cwds/neutron/atom/AtomLoadStepHandler.java, src/main/java/gov/ca/cwds/neutron/flight/FlightLog.java, src/main/java/gov/ca/cwds/neutron/inject/HyperCube.java, src/main/java/gov/ca/cwds/neutron/launch/NeutronRocket.java, src/main/java/gov/ca/cwds/neutron/launch/RocketFactory.java, src/main/java/gov/ca/cwds/neutron/launch/StandardFlightSchedule.java, src/main/java/gov/ca/cwds/neutron/launch/ZombieKillerTimerTask.java, src/main/java/gov/ca/cwds/neutron/launch/listener/NeutronSchedulerListener.java, src/main/java/gov/ca/cwds/neutron/rocket/ExitInitialLoadRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/IndexResetRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/LastFlightRocket.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryLastChangeHandler.java, src/main/java/gov/ca/cwds/neutron/rocket/PeopleSummaryThreadHandler.java, src/main/java/gov/ca/cwds/neutron/util/shrinkray/NeutronStringUtils.java, src/main/resources/neutron/elasticsearch/setting/people-summary-index-settings.json, src/test/java/gov/ca/cwds/jobs/test/NeutronPlayground.java
Fixes for SNAP-784 and SNAP-785.
=> Dave SNAP-784 redux

build.gradle
Jobs project to use the same version of Commons IO as api-core.
=> Jar conflict: use same Common IO version as api-core

Jenkinsfile, build.gradle
https://osi-cwds.atlassian.net/browse/FIT-352
=> Build a Jenkins PR pipeline and Master pipeline for Neutron Jobs Project

Jenkinsfile
=> (FIT-352) Jenkins pipelines for Neutron Jobs Project

src/main/java/gov/ca/cwds/jobs/ReportFaultCANSClientIdsJob.java
[Cans 886 Leverage IBM MRHIST_T Table for CANS Merged Clients fix](https://osi-cwds.atlassian.net/browse/CANS-886)
=> Cans 886 Leverage IBM MRHIST_T Table for CANS Merged Clients fix

src/main/java/gov/ca/cwds/jobs/ReportFaultCANSClientIdsJob.java
fix to update person_id in assessment_aud table.
=> CANS-886 Leverage IBM MRHIST_T Table for CANS Merged Clients

build.gradle
used api-core version that implements SNAP-816
=> SNAP-816 Search Date of Birth in Different Date Formats

build.gradle
updated api-core version which contains the code change for SNAP-46
=> SNAP-846 Search Date of Birth in Different Date Formats

src/main/java/gov/ca/cwds/neutron/flight/FlightLog.java, src/test/java/gov/ca/cwds/jobs/ReferralHistoryIndexerJobTest.java, src/test/java/gov/ca/cwds/neutron/rocket/BasePersonRocketTest.java, src/test/java/gov/ca/cwds/neutron/rocket/CaseRocketTest.java
Junit and Javadoc cleanup. Trigger Jenkins build.
=> Dave javadoc junit

build.gradle
updated api-core version which contains required changes.
=> SNAP-953 Search by Sex At Birth
